import {workflow,node,trigger,newCredential,expr} from '@n8n/workflow-sdk';
const credential=newCredential('Schulze Portal Supabase','MpEnClmtG7bhzNBS');
const endpoint='https://zwtmlrzwqnluosrdbjfv.supabase.co/functions/v1/portal-airtable-events/';
const notify=trigger({type:'n8n-nodes-base.webhook',version:2.1,config:{name:'Receive verified event wake',parameters:{httpMethod:'POST',path:'schulze-portal-realtime-wake',responseMode:'onReceived',options:{noResponseBody:true}},position:[0,0]},output:[{body:{proof:'example'}}]});
const recover=trigger({type:'n8n-nodes-base.scheduleTrigger',version:1.3,config:{name:'Recover queued events every minute',parameters:{rule:{interval:[{field:'minutes',minutesInterval:1}]}},position:[0,300]},output:[{}]});
const manual=trigger({type:'n8n-nodes-base.manualTrigger',version:1,config:{name:'Recover pending portal events',parameters:{},position:[0,500]},output:[{}]});
const proof=node({type:'n8n-nodes-base.code',version:2,config:{name:'Accept wake proof only',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const p=$input.first().json.body?.proof;if(typeof p!=='string'||!/^([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){2}$/.test(p))return [];return [{json:{proof:p}}];"},position:[280,0]},output:[{proof:'example'}]});
const recovery=node({type:'n8n-nodes-base.code',version:2,config:{name:'Request trusted queue recovery',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:'return [{json:{recovery:true}}];'},position:[280,300]},output:[{recovery:true}]});
const claim=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Claim pending portal sync',parameters:{method:'POST',url:endpoint+'claim',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr('{{ $json }}'),options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:credential},position:[550,120]},output:[{run:true,leaseId:'example'}]});
const lease=node({type:'n8n-nodes-base.code',version:2,config:{name:'Require sync lease',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const j=$input.first().json;if(j.run===false)return [];if(j.run!==true||typeof j.leaseId!=='string'||!/^[a-f0-9-]{36}$/.test(j.leaseId))throw new Error('invalid_sync_lease');return [{json:j}];"},position:[820,120]},output:[{run:true,leaseId:'example'}]});
const sync=node({type:'n8n-nodes-base.executeWorkflow',version:1.3,config:{name:'Run atomic portal snapshot',parameters:{source:'database',workflowId:{__rl:true,mode:'id',value:'m2Yri8eiqX2cO6DD'},mode:'once',options:{waitForSubWorkflow:true}},position:[1090,120]},output:[{ok:true}]});
const ack=node({type:'n8n-nodes-base.code',version:2,config:{name:'Require confirmed snapshot',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"if($input.first().json.ok!==true)throw new Error('portal_snapshot_not_confirmed');return [{json:{leaseId:$('Require sync lease').first().json.leaseId}}];"},position:[1360,120]},output:[{leaseId:'example'}]});
const complete=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Complete lease and drain later edits',parameters:{method:'POST',url:endpoint+'complete',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr('{{ $json }}'),options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:credential},position:[1630,120]},output:[{ok:true}]});
export default workflow('schulze-portal-realtime-worker','Schulze Portal · Realtime sync worker')
.add(notify).to(proof).to(claim).to(lease).to(sync).to(ack).to(complete)
.add(recover).to(recovery).to(claim)
.add(manual).to(recovery);
