import {workflow,node,trigger,newCredential,expr,splitInBatches,nextBatch} from '@n8n/workflow-sdk';
const bearer=newCredential('Schulze Portal Supabase','MpEnClmtG7bhzNBS');
const airtable=newCredential('Schulze x Apex Airtable','oun3u0zdIMOShiCK');
const endpoint='https://zwtmlrzwqnluosrdbjfv.supabase.co/functions/v1/portal-airtable-events/';
const manual=trigger({type:'n8n-nodes-base.manualTrigger',version:1,config:{name:'Register or renew portal hooks',parameters:{},position:[0, 0]},output:[{}]});
const schedule=trigger({type:'n8n-nodes-base.scheduleTrigger',version:1.3,config:{name:'Renew portal hooks every 12 hours',parameters:{rule:{interval:[{field:'hours',hoursInterval:12}]}},position:[0, 200]},output:[{}]});
const claim=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Claim exclusive hook maintenance',parameters:{method:'POST',url:endpoint+'maintenance-claim',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:'{}',options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:bearer},position:[260, 0]},output:[{run:true,leaseId:'example'}]});
const requireLease=node({type:'n8n-nodes-base.code',version:2,config:{name:'Require maintenance lease',parameters:{mode:'runOnceForAllItems',jsCode:"const j=$input.first().json;if(j.run===false)return [];if(j.run!==true||typeof j.leaseId!=='string'||!/^[a-f0-9-]{36}$/.test(j.leaseId))throw new Error('invalid_maintenance_lease');return [{json:j}];"},position:[520, 0]},output:[{run:true,leaseId:'example'}]});
const loop=splitInBatches({version:3,config:{name:'Maintain one hook at a time',parameters:{batchSize:1,options:{}},position:[1560, 0]}});
const cleanup=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Remove expired owned hook or confirm metadata',parameters:{method:expr("{{ $json.retireRemote ? 'DELETE' : 'GET' }}"),url:expr("{{ 'https://api.airtable.com/v0/bases/appAutw0Fvsuk2pfJ/webhooks' + ($json.retireRemote ? '/' + $json.retireRemote : '') }}"),authentication:'predefinedCredentialType',nodeCredentialType:'airtableTokenApi',options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json',fullResponse:true}},timeout:20000}},credentials:{airtableTokenApi:airtable},position:[1820, 350]},output:[{statusCode:204}]});
const cleaned=node({type:'n8n-nodes-base.code',version:2,config:{name:'Require owned remote cleanup',parameters:{mode:'runOnceForAllItems',jsCode:"const status=$input.first().json.statusCode;if(!Number.isInteger(status)||status<200||status>=300)throw new Error('hook_cleanup_failed');return [{json:$('Maintain one hook at a time').item.json}];"},position:[2080, 350]},output:[{tableId:'tblH1iaekZP1YRh2m',id:null,action:'register',request:{}}]});
const remote=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Read Airtable webhook metadata',parameters:{method:'GET',url:'https://api.airtable.com/v0/bases/appAutw0Fvsuk2pfJ/webhooks',authentication:'predefinedCredentialType',nodeCredentialType:'airtableTokenApi',options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{airtableTokenApi:airtable},position:[780, 0]},output:[{webhooks:[]}]});
const registry=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Read private portal hook registry',parameters:{method:'POST',url:endpoint+'registry',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:'{}',options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:bearer},position:[1040, 0]},output:[{hooks:[]}]});
const prep=node({type:'n8n-nodes-base.code',version:2,config:{name:'Prepare hook maintenance',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const hooks=$input.first().json.hooks;\nconst remote=$('Read Airtable webhook metadata').first().json.webhooks;\nif(!Array.isArray(hooks)||!Array.isArray(remote))throw new Error('invalid_hook_registry');\nconst tables=['tblfPwZLXgjYuFMsc','tbln087XtgwIP7HPG','tblYeDa6ZbNL5YGTb','tblf2AsiyZTb306JQ','tblH1iaekZP1YRh2m'];\nconst notificationUrl='https://zwtmlrzwqnluosrdbjfv.supabase.co/functions/v1/portal-airtable-events/notify';\nreturn tables.map(tableId=>{\n const found=hooks.filter(h=>h.table_id===tableId);\n if(found.length>1)throw new Error('duplicate_hook_registry');\n let id=found[0]?.webhook_id;let retireId=null,retireRemote=null;\n const own=remote.filter(h=>h.notificationUrl===notificationUrl&&h.specification?.options?.filters?.recordChangeScope===tableId);\n const live=remote.find(h=>h.id===id);\n if(id&&!live){retireId=id;id=null;}\n if((!id&&own.length)||(id&&(own.length!==1||own[0].id!==id)))throw new Error('portal_hook_registry_mismatch');\n if(id&&!/^ach[A-Za-z0-9]+$/.test(id))throw new Error('invalid_hook_id');\n if(id&&(live.isHookEnabled===false||(live.expirationTime&&Date.parse(live.expirationTime)<=Date.now()))){retireId=id;retireRemote=id;id=null;}\n return {json:{tableId,id:id||null,retireId,retireRemote,action:id?'renewed':'register',request:id?{}:{notificationUrl,specification:{options:{filters:{dataTypes:['tableData','tableFields','tableMetadata'],recordChangeScope:tableId}}}}}};\n});"},position:[1300, 0]},output:[{tableId:'tblH1iaekZP1YRh2m',id:null,action:'register',request:{}}]});
const prepare=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Retire only missing owned hooks',parameters:{method:'POST',url:endpoint+'prepare',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr('{{ $json }}'),options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:bearer},position:[2340, 350]},output:[{tableId:'tblH1iaekZP1YRh2m',id:null,action:'register',request:{}}]});
const api=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Create or refresh Airtable hook',onError:'continueRegularOutput',parameters:{method:'POST',url:expr("{{ 'https://api.airtable.com/v0/bases/appAutw0Fvsuk2pfJ/webhooks' + ($json.id ? '/' + $json.id + '/refresh' : '') }}"),authentication:'predefinedCredentialType',nodeCredentialType:'airtableTokenApi',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr('{{ $json.request }}'),options:{batching:{batch:{batchSize:1,batchInterval:300}},redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json',fullResponse:true,neverError:true}},timeout:20000}},credentials:{airtableTokenApi:airtable},position:[2600, 350]},output:[{statusCode:200,body:{id:'ach12345678901234',expirationTime:'2026-09-24T00:00:00Z',macSecretBase64:'runtime-only'}}]});
const persist=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Store signing key in Vault or renewal date',retryOnFail:true,maxTries:3,waitBetweenTries:1000,parameters:{method:'POST',url:expr("{{ 'https://zwtmlrzwqnluosrdbjfv.supabase.co/functions/v1/portal-airtable-events/' + ($json.statusCode >= 200 && $json.statusCode < 300 ? $('Maintain one hook at a time').item.json.action : 'maintenance-error') }}"),authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr("{{ $json.statusCode >= 200 && $json.statusCode < 300 ? {id:$json.body.id || $('Maintain one hook at a time').item.json.id,tableId:$('Maintain one hook at a time').item.json.tableId,expirationTime:$json.body.expirationTime,macSecretBase64:$json.body.macSecretBase64} : {status:$json.statusCode} }}"),options:{batching:{batch:{batchSize:1,batchInterval:200}},redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:bearer},position:[2860, 350]},output:[{ok:true,webhookId:'ach12345678901234'}]});
const enable=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Ensure Airtable notifications enabled',parameters:{method:'POST',url:expr("{{ 'https://api.airtable.com/v0/bases/appAutw0Fvsuk2pfJ/webhooks/' + ($json.webhookId || $('Maintain one hook at a time').item.json.id) + '/enableNotifications' }}"),authentication:'predefinedCredentialType',nodeCredentialType:'airtableTokenApi',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:'{"enable":true}',options:{batching:{batch:{batchSize:1,batchInterval:300}},redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json',fullResponse:true}},timeout:20000}},credentials:{airtableTokenApi:airtable},position:[3120, 350]},output:[{statusCode:200}]});
const catchup=node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{name:'Queue catch-up snapshot',executeOnce:true,parameters:{method:'POST',url:endpoint+'catchup',authentication:'genericCredentialType',genericAuthType:'httpBearerAuth',sendBody:true,contentType:'json',specifyBody:'json',jsonBody:expr("{{ {leaseId:$('Require maintenance lease').first().json.leaseId} }}"),options:{redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}},timeout:20000}},credentials:{httpBearerAuth:bearer},position:[2080, 0]},output:[{ok:true}]});
const done=node({type:'n8n-nodes-base.code',version:2,config:{name:'Confirm hook maintenance',parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const rows=$input.all();if(rows.length!==5||rows.some(i=>!Number.isInteger(i.json.statusCode)||i.json.statusCode<200||i.json.statusCode>=300))throw new Error('hook_maintenance_incomplete');return [{json:{ok:true,hooks:rows.length}}];"},position:[1820, 0]},output:[{ok:true,hooks:5}]});
export default workflow('schulze-portal-realtime-hooks','Schulze Portal · Airtable webhook maintenance')
.add(manual).to(claim).to(requireLease).to(remote).to(registry).to(prep)
.to(loop.onEachBatch(cleanup.to(cleaned).to(prepare).to(api).to(persist).to(enable).to(nextBatch(loop))).onDone(done.to(catchup)))
.add(schedule).to(claim);
